---
title: "Course Syllabus"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE,
                      comment = "")
```

Last Updated: `r format(Sys.Date(), "%m/%d/%Y")`

# Course Title {#title}

PSY:5330 – Principles of Psychological Assessment (Spring 2024)

# Course Meeting Time and Place {#lectureTime}

Tuesday & Thursday 11:00 a.m.–12:15 p.m., 109 Stuit Hall (STH)

# Course Website {#website}

https://icon.uiowa.edu

To access the course site, log into [Iowa Courses Online (ICON)](https://icon.uiowa.edu) using your Hawk ID and password.

# Course Home {#home}

The College of Liberal Arts and Sciences (CLAS) is the home of this course, and CLAS governs the add and drop deadlines, the "second-grade only" option (SGO), academic misconduct policies, and other policies and procedures.
Other UI colleges may have different policies.

# Instructor {#instructor}

Professor Petersen\
Office: 175 Psychological and Brain Sciences Building (PBSB)\
E-mail: [isaac-t-petersen@uiowa.edu](mailto:isaac-t-petersen@uiowa.edu)\
Office Phone: 467-1014\
Office Hours: by appointment\

# Departmental Resources {#deptResources}

Department of Psychological and Brain Sciences: [https://psychology.uiowa.edu](https://psychology.uiowa.edu)\
Department of Psychological and Brain Sciences Main Office: G60 Psychological and Brain Sciences Building (335-2406)\
Director of Graduate Studies: Ryan LaLumiere ([ryan-lalumiere@uiowa.edu](mailto:ryan-lalumiere@uiowa.edu); 335-3681)\
Chair of Department: Professor Blumberg ([mark-blumberg@uiowa.edu](mailto:mark-blumberg@uiowa.edu); 335-2424)

# Prerequisites {#prereqs}

To succeed in the class, it is helpful to have foundational understanding of correlation and multiple regression.

# Description of Course {#description}

In this course, we examine basic psychometrics and the background, development, evaluation, administration, scoring, integration, and interpretation of selected techniques in psychological assessment.
The course applies a scientific perspective to psychological assessment.
*You are urged to reconsider your decision to take this class if you are reluctant to examine these topics in a scientific manner.*

# Learning Objectives {#objectives}

This course is focused on important principles of psychological assessment, not on application.
The goal of the class is to give you lots of "thinking tools" relevant to psychological assessment—i.e., "how to think" about and critically evaluate assessments in psychology—to help you advance your research program.

# Course Book {#textbook}

I want those who are interested to be in the best position to apply the principles we discuss.
Thus, I created a companion book for the course that includes practical data and analysis examples to help you better understand the principles and how to apply them in your own research.
The course book includes exercises to help you test your comprehension.
You are not required or expected to read it for this class.
It is merely meant to be a helpful supplementary resource for those who are interested.
You can access the book here: https://isaactpetersen.github.io/Principles-Psychological-Assessment

# Academic Honesty and Misconduct {#academicHonesty}

All students in CLAS courses are expected to abide by the [CLAS Code of Academic Honesty](https://clas.uiowa.edu/students/handbook/academic-fraud-honor-code).
Academic misconduct must be reported by instructors to CLAS according to [these procedures](https://clas.uiowa.edu/students/handbook/academic-fraud-honor-code).
Please note that collaboration with other classmates on quizzes and during exams is not permitted.
However, I do encourage you to collaborate with classmates to *prepare* for exams (e.g., informal study groups).

# Course Requirements and Policies {#requirements}

- [Assigned readings](#readings)
- [Class participation](#attendanceParticipation)
- [Midterm Exam](#exams)
- [Final Exam](#exams)
- [Paper](#paper)

## Lecture {#lecture}

The course is primarily lecture.
We will meet twice weekly for lectures, at the time and location described [above](#lectureTime).
There is considerable material to cover, and we will move quickly.
You should feel free to ask questions during lecture, although some questions may need to be deferred given the need to complete coverage of specific material.
<u>Questions and further discussion of class material are always welcome</u> during office hours and via e-mail.
Please bear in mind that extensive or complex questions may not be addressable over e-mail.

### Lecture Recordings {#recordings}

My intention is to record lectures so that you may review them.
Recorded lectures will be posted on the "UICapture" tab in [ICON](https://icon.uiowa.edu).
Recordings will be available up to 48 hours after class (for Thursday lectures) or until the Thursday class period (for Tuesday lectures).
However, <u>please do not count on recordings being available</u>, in case I accidentally forget to initiate the recording or there is a technical malfunction.
The availability of lecture recordings will not be extended beyond 48 hours after lecture—the recordings are meant to help people keep up with lectures and for students to retrieve the relevant content if they missed anything during the live lecture or if they miss the lecture; they are not meant to be a study method that allows people to fall behind in class from week to week.
If you miss something and are unable to watch the lecture recording, you can get/review notes with a peer, and then come to office hours if you have specific questions.

## Attendance and Participation {#attendanceParticipation}

Attendance and participation are strongly encouraged to maximize your and others' learning.

## Readings {#readings}

Readings and other materials will be posted on [ICON](https://icon.uiowa.edu).
Doing the relevant readings before each class will help you best come prepared to learn the material presented in class.

## Examinations {#exams}

There will be 2 exams.
The exams will be short answer/essay questions.
The final exam is non-cumulative; each exam will emphasize information presented for the half of the class that precedes it.
However, some integration of information will be required for questions on the second exam.
Exam questions can come from lectures or required readings.

### Missing Exams {#missingExams}

Students are allowed to make up exams that have been missed due to illness, mandatory religious observations, official University activities, or other unavoidable circumstances.
Note: the format of the make-up exam may differ from the original exam.
If you know that you must be away at the time of an exam for one of these reasons, please contact me in advance whenever possible to schedule a make-up exam.

## Paper {#paper}

You will write a final/term paper on a topic pertaining to assessment.
The paper can be a literature review pertaining to assessment (with recommendations), or it can be a paper on the development of an assessment technique.
The goal is for the paper to be as relevant to your research interests as possible, so it directly advances your research program.
Please do not stress about the paper.
Your paper should be less than 20 pages (excluding references).
It is okay (and encouraged!) for you to use, as your paper, something that you are already working on or to write a paper that you are submitting for another assignment—consider writing a paper that could be a publication.
I want to keep the topic requirements of the paper flexible and open-ended so the paper can be as relevant for your research program as possible—the only requirement is that the paper topic is relevant to assessment, and that your paper incorporates ideas we discuss in class.

Your final paper is due before the last class (<u>**Deadline: 11 am on Thursday, May 2**</u>).
Please submit your paper via [ICON](https://icon.uiowa.edu).

# Articles {#articles}

\*Designates a paper that you should read, get the basic idea, and remember where to find it if you need further information.
These are typically historical papers, illustrations of specific techniques, or useful references.

## Psychometrics, Prediction, and General Issues

### Science and the Replication Crisis {#section1}

<div style="text-indent: -40px; padding-left: 40px;">

#### <u>Section 1</u> {.unnumbered}

Loken, E., & Gelman, A. (2017). Measurement error and the replication crisis. *Science, 355*(6325), 584–585. https://doi.org/10.1126/science.aal3618

McFall, R. M. (1991). Manifesto for a science of clinical psychology. *The Clinical Psychologist, 44*(6), 75–91.

McFall, R. M. (2000). Elaborate reflections on a simple manifesto. *Applied & Preventive Psychology, 9*(1), 5–21. https://doi.org/10.1016/s0962-1849(05)80035-6

### Reliability {#section2}

<u>Section 2</u>

McNeish, D. (2018). Thanks coefficient alpha, we’ll take it from here. *Psychological Methods, 23*(3), 412–433. https://doi.org/10.1037/met0000144

\*Galton, F. (1948). Classification of men according to their natural gifts, 1869. In W. Dennis (Ed.), *Readings in the history of psychology* (pp. 231–247). Appleton-Century-Crofts. https://psycnet.apa.org/record/2006-10213-000 

\*Garland, L. H. (1960). The problem of observer error. *Bulletin of the New York Academy of Medicine, 36*(9), 570–584.

#### <u>Section 3</u> {.unnumbered #section4}

<u>Section 3</u>

Schmidt, F. L., & Hunter, J. E. (1996). Measurement error in psychological research: Lessons from 26 research scenarios. *Psychological Methods, 1*(2), 199–223. https://doi.org/10.1037/1082-989X.1.2.199

Wiggins, J. S. (1973). Observational techniques: I. Generalizability and facets of observation. In J. S. Wiggins (Ed.), *Personality and prediction: Principles of personality assessment* (pp. 277–295). Addison-Wesley.

### Validity {#section4}

<u>Section 4</u>

Campbell, D. T., & Fiske, D. W. (1959). Convergent and discriminant validation by the multitrait-multimethod matrix. *Psychological Bulletin, 56*(2), 81–105. https://doi.org/10.1037/h0046016 

Hayes, S. C., Nelson, R. O., & Jarrett, R. B. (1987). The treatment utility of assessment: A functional approach to evaluating assessment quality. *American Psychologist, 42*, 963–974. https://doi.org/10.1037/0003-066X.42.11.963 

Meehl, P. E. (1973). Chapter 1. *Psychodiagnosis: Selected papers*. University of Minnesota Press. [This is Cronbach, L. J., & Meehl, P. E. (1955). Construct validity in psychological tests. *Psychological Bulletin, 52*(4), 281–302. https://doi.org/10.1037/h0040957]

<u>Section 5</u>

Sechrest, L. (1963). Incremental validity: A recommendation. *Educational and Psychological Measurement, 23*, 153–158. https://doi.org/10.1177/001316446302300113 

Shavelson, R. J., Webb, N. M., & Rawley, R. L. (1989). Generalizability theory. *American Psychologist, 44*, 922–932. https://doi.org/10.1037/0003-066X.44.6.922 

Bornstein, R. F. (2011). Toward a process-focused model of test score validity: Improving psychological assessment in science and practice. *Psychological Assessment, 23*(2), 532–544. https://doi.org/10.1037/a0022402

\*American Educational Research Association, American Psychological Association, & National Council on Measurement in Education. (2014). *Standards for educational and psychological testing*. American Educational Research Association. [This is available in the clinic library. You don’t need to read this for our class, but you should know it exists as a reference, because it sets the standard for APA journals, licensure exams, and beyond.]

### Emerging Perspectives in Measurement

#### Structural Equation Modeling (SEM)

<u>Section 6</u>

Bollen, K. A., & Lennox, R. D. (1991). Conventional wisdom on measurement: A structural equation perspective. *Psychological Bulletin, 110*(2), 305–314. https://doi.org/10.1037/0033-2909.110.2.305 

Podsakoff, P. M., MacKenzie, S. B., & Podsakoff, N. P. (2012). Sources of method bias in social science research and recommendations on how to control it. *Annual Review of Psychology, 63*(1), 539–569. https://doi.org/10.1146/annurev-psych-120710-100452 

Edwards, J. R., & Bagozzi, R. P. (2000). On the nature and direction of relationships between constructs and measures. *Psychological Methods, 5*(2), 155–174. https://doi.org/10.1037/1082-989X.5.2.155 [read pp. 155–162 carefully, but don’t worry about the complex path models that follow unless they are relevant to your own research.]

#### Item Response Theory (IRT)

<u>Section 7</u>

Embretson, S. E. (1996). The new rules of measurement. *Psychological Assessment, 8*, 341–349. https://doi.org/10.1037/1040-3590.8.4.341

Krueger, R. F., Nichol, P. E., Hicks, B. M., Markon, K. E., Patrick, C. J., lacono, W. G., & McGue, M. (2004). Using latent trait modeling to conceptualize an alcohol problems continuum. *Psychological Assessment, 16*(2), 107–119. https://doi.org/10.1037/1040-3590.16.2.107

Cooper, L. D., & Balsis, S. (2009). When less is more: How fewer diagnostic criteria can indicate greater severity. *Psychological Assessment, 21*(3), 285–293. https://doi.org/10.1037/a0016698

Reise, S. P., & Waller, N. G. (2009). Item response theory and clinical measurement. *Annual Review of Clinical Psychology, 5*(1), 27–48. https://doi.org/10.1146/annurev.clinpsy.032408.153553

## Prediction

### Basics

<u>Section 8</u>

Meehl, P. E. (1973). Chapter 2. *Psychodiagnosis: Selected papers*. University of Minnesota Press. [This is Meehl, P. E., & Rosen, A. (1955). Antecedent probability and the efficiency of psychometric signs, patterns, or cutting scores. *Psychological Bulletin, 52*(3), 194–216. https://doi.org/10.1037/h0048070]

### Signal Detection Theory

<u>Section 9</u>

Treat, T. A., & Viken, R. J. (2012). Measuring test performance with signal detection theory techniques. In H. Cooper (Ed.), *Handbook of research methods in psychology: Foundations, planning, measures, and psychometrics* (Vol. 1, pp. 723–744). American Psychological Association. https://doi.org/10.1037/13619-038

Swets, J. A., Dawes, R. M., & Monahan, J. (2000). Psychological science can improve diagnostic decisions. *Psychological Science in the Public Interest, 1*(1), 1–26. https://doi.org/10.1111/1529-1006.001

Lindhiem, O., Petersen, I. T., Mentch, L. K., & Youngstrom, E. A. (2020). The importance of calibration in clinical psychology. *Assessment, 27*(4), 840–854. https://doi.org/10.1177/1073191117752055 

### Clinical Judgment vs. Algorithmic Prediction

<u>Section 10</u>

Garb, H. N. (2005). Clinical judgment and decision making. *Annual Review of Clinical Psychology, 1*, 67–89. https://doi.org/10.1146/annurev.clinpsy.1.102803.143810

Dawes, R. M., Faust, D., & Meehl, P. E. (1989). Clinical versus actuarial judgment. *Science, 243*(4899), 1668–1674. https://doi.org/10.1126/science.2648573 

Dawes, R. M. (1986). Representative thinking in clinical judgment. *Clinical Psychology Review, 6*, 425–441. https://doi.org/10.1016/0272-7358(86)90030-9

Youngstrom, E. A., Halverson, T. F., Youngstrom, J. K., Lindhiem, O., & Findling, R. L. (2018). Evidence-based assessment from simple clinical judgments to statistical learning: Evaluating a range of options using pediatric bipolar disorder as a diagnostic challenge. *Clinical Psychological Science, 6*(2), 243–265. https://doi.org/10.1177/2167702617741845

## General Issues in Clinical Assessment

<u>Section 11</u>

\*Benjamin, L. T. (2005). A history of clinical psychology as a profession in America (and a glimpse of its future). *Annual Review of Clinical Psychology, 1*, 1–30. https://doi.org/10.1146/annurev.clinpsy.1.102803.143758

Kazdin, A. E. (1995). Preparing and evaluating research reports. *Psychological Assessment, 7*(3), 228–237. https://doi.org/10.1037/1040-3590.7.3.228

Sechrest, L., Stickle, T. R., & Stewart, M. (1998). The role of assessment in clinical psychology. In A. Bellack, M. Hersen, & C. R. Reynolds (Eds.), *Comprehensive clinical psychology* (Vol. 4: Assessment). Pergamon.

## Evidence-Based Assessment

<u>Section 12</u>

Hunsley, J., & Mash, E. J. (2007). Evidence-based assessment. *Annual Review of Clinical Psychology, 3*, 29–51. https://doi.org/10.1146/annurev.clinpsy.3.022806.091419 

Antony, M. M., & Rowa, K. (2005). Evidence-based assessment of anxiety disorders in adults. *Psychological Assessment, 17*(3), 256–266. https://doi.org/10.1037/1040-3590.17.3.256 [This is a case study in evidence-based assessment—it’s the general approach that matters, not what is specific about anxiety.]

Youngstrom, E. A., & Van Meter, A. (2016). Empirically supported assessment of children and adolescents. *Clinical Psychology: Science and Practice, 23*(4), 327–347. https://doi.org/10.1111/cpsp.12172 

Youngstrom, E. A., Van Meter, A., Frazier, T. W., Hunsley, J., Prinstein, M. J., Ong, M.-L., & Youngstrom, J. K. (2017). Evidence-based assessment as an integrative model for applying psychological science to guide the voyage of treatment. *Clinical Psychology: Science and Practice, 24*(4), 331–363. https://doi.org/10.1111/cpsp.12207 

## Ethical Issues in Assessment

<u>Section 13</u>

American Psychological Association. (2017). Ethical principles of psychologists and code of conduct. https://www.apa.org/ethics/code (Sections 1, 2, 9).

Nagy, T. F. (2011). Ethics in psychological assessment. In T. F. Nagy (Ed.), *Essential ethics for psychologists: a primer for understanding and mastering core issues* (pp. 171–183). American Psychological Association. https://doi.org/10.1037/12345-009

Campbell, L., Vasquez, M., Behnke, S., & Kinscherff, R. (2010). Assessment. In L. Campbell, M. Vasquez, S. Behnke, & R. Kinscherff (Eds.), *APA Ethics Code commentary and case illustrations*. American Psychological Association. 

Bersoff, D. N., DeMatteo, D., & Foster, E. E. (2012). Assessment and testing. In S. J. Knapp (Ed.), *APA handbook of ethics in psychology* (Vol. 2: Practice, Teaching, and Research, pp. 45–74). American Psychological Association. 

\*Tackett, J. L., Brandes, C. M., & Reardon, K. W. (2019). Leveraging the Open Science Framework in clinical psychological assessment research. *Psychological Assessment, 31*(12), 1386–1394. https://doi.org/10.1037/pas0000583

## Intellectual Assessment

<u>Section 15</u>

Ackerman, P. L. (2013). Assessment of intellectual functioning in adults. In K. F. Geisinger, J. F. Carlson, J.-I. C. Hansen, N. R. Kuncel, S. P. Reise, & M. C. Rodriguez (Eds.), *APA handbook of testing and assessment in psychology* (Vol. 2: Testing and Assessment in Clinical and Counseling Psychology, pp. 119–132). American Psychological Association. https://doi.org/10.1037/14048-008

\*Binet, A., & Simon, T. (1948). Upon the necessity of establishing a scientific diagnosis of inferior states of intelligence. In W. Dennis (Ed.), *Readings in the history of psychology* (pp. 407–411). Appleton-Century-Crofts.

\*Binet, A., & Simon, T. (1948). The development of the Binet-Simon Scale, 1905–1908. In W. Dennis (Ed.), *Readings in the history of psychology* (pp. 412–424). Appleton-Century-Crofts. 

\*Cattell, J. M. (1948). Mental tests and measurements, 1890. In W. Dennis (Ed.), *Readings in the history of psychology* (pp. 347–354). Appleton-Century-Crofts.

<u>Section 16</u>

McClelland, D. C. (1973). Testing for competence rather than for "intelligence.". American Psychologist, 28, 1–14. https://doi.org/10.1037/h0034092 See also paper by Barrett and Depinet (1991), A reconsideration of Testing for Competence rather than for intelligence, *American Psychologist, 46*, 1012–1024; and McClelland and various others in reply (1994), *American Psychologist, 49*, 64–71

### Bias

<u>Section 17</u>

Cole, N. S. (1981). Bias in testing. *American Psychologist, 36*(10), 1067–1077. https://doi.org/10.1037/0003-066X.36.10.1067 

Sackett, P. R., & Wilk, S. L. (1994). Within-group norming and other forms of score adjustment in preemployment testing. *American Psychologist, 49*(11), 929–954. https://doi.org/10.1037/0003-066X.49.11.929 

<u>Section 18</u>

Sackett, P. R., Schmitt, N., Ellingson, J. E., & Kabin, M. B. (2001). High-stakes testing in employment, credentialing, and higher education. *American Psychologist, 56*, 301–318. https://doi.org/10.1037/0003-066X.56.4.302 

Sackett, P. R., Borneman, M. J., & Connelly, B. S. (2008). High stakes testing in higher education and employment: Appraising the evidence for validity and fairness. *American Psychologist, 63*, 215–227. https://doi.org/10.1037/0003-066X.63.4.215

## The Interview and the DSM

<u>Section 19</u>

Faraone, S. V., & Tsuang, M. T. (1994). Measuring diagnostic accuracy in the absence of a "gold standard". *American Journal of Psychiatry, 151*, 650–657. https://doi.org/10.1176/ajp.151.5.650

\*Sullivan, H. S. (1970). *The psychiatric interview*. Norton. Chapters 1–4, 7 [This is available in the UI library. You don't need to read it for this class. But you should read it at some point, as an example of a master clinician assessing patients by way of interview.]

Summerfeldt, L. J., Kloosterman, P. H., & Antony, M. M. (2010). Structured and semistructured diagnostic interviews. In M. M. Antony & D. H. Barlow (Eds.), *Handbook of assessment and treatment planning for psychological disorders* (2nd ed., pp. 95–137). Guilford Press. 

Mullins-Sweatt, S. N., & Widiger, T. A. (2009). Clinical utility and DSM-V. *Psychological Assessment, 21*(3), 302–312. https://doi.org/10.1037/a0016607

Sharp, K. L., Williams, A. J., Rhyner, K. T., & Ilardi, S. S. (2013). The clinical interview. In K. F. Geisinger, J. F. Carlson, J.-I. C. Hansen, N. R. Kuncel, S. P. Reise, & M. C. Rodriguez (Eds.), *APA handbook of testing and assessment in psychology* (Vol. 2: Testing and assessment in clinical and counseling psychology, pp. 103–117). American Psychological Association. https://doi.org/10.1037/14048-007

## Assessment of personality and other symptomatology

### Objective tests

<u>Section 20</u>

Burisch, M. (1984). Approaches to personality inventory construction: A comparison of merits. *American Psychologist, 39*, 214–227. https://doi.org/10.1037/0003-066X.39.3.214

Clark, L. A., & Watson, D. (2019). Constructing validity: New developments in creating objective measuring instruments. *Psychological Assessment, 31*(12), 1412–1427. https://doi.org/10.1037/pas0000626
Floyd, F. J., & Widaman, K. F. (1995). Factor analysis in the development and refinement of clinical assessment instruments. *Psychological Assessment, 7*, 286–299. https://doi.org/10.1037/1040-3590.7.3.286

<u>Section 21</u>

\*Graham, J. R. (2022). *MMPI instruments: Assessing personality and psychopathology* (6th ed.). Oxford University Press. (Chapters 1–5). [This is available in the clinic library. Get a feel for this measure and the way it was developed, you don’t need to remember details about the scales.]

Sellbom, M. (2019). The MMPI-2-Restructured Form (MMPI-2-RF): Assessment of personality and psychopathology in the twenty-first century. *Annual Review of Clinical Psychology, 15*(1), 149–177. https://doi.org/10.1146/annurev-clinpsy-050718-095701

Wiggins, J. S. (1973). Structured techniques. In J. S. Wiggins (Ed.), *Personality and prediction: Principles of personality assessment* (pp. 380–440). Addison-Wesley.

<u>Section 22</u>

Dunning, D., Heath, C., & Suls, J. M. (2004). Flawed self-assessment: Implications for health, education, and the workplace. *Psychological Science in the Public Interest, 5*, 69–106. https://doi.org/10.1111/j.1529-1006.2004.00018.x

Krosnick, J. A. (1999). Survey research. *Annual Review of Psychology, 50*, 537–567. https://doi.org/10.1146/annurev.psych.50.1.537

### Projective tests

<u>Section 23</u>

\*Frank, L. K. (1939). Projective methods for the study of personality. *Journal of Psychology, 8*, 389–413. https://doi.org/10.1080/00223980.1939.9917671

\*Lindzey, G. (1952). Thematic Apperception Test: Interpretive assumptions and related empirical evidence. *Psychological Bulletin, 49*, 1–25. https://doi.org/10.1037/h0062363

Lilienfeld, S. O., Wood, J. M., & Garb, H. N. (2000). The scientific status of projective techniques. *Psychological Science in the Public Interest, 1*, 27–66. https://doi.org/10.1111/1529-1006.002

\*Wood, J. M., Nezworski, M. T., & Stejskal, W. J. (1996). The comprehensive system for the Rorschach: A critical examination. *Psychological Science, 7*(1), 3–10. https://doi.org/10.1111/j.1467-9280.1996.tb00658.x. Also response from Exner and reply by Wood et al. on pp. 11–17.

### Psychophysiological Measures and RDoC

<u>Section 24</u>

Dubois, J., & Adolphs, R. (2016). Building a science of individual differences from fMRI. *Trends in Cognitive Sciences, 20*(6), 425–443. https://doi.org/10.1016/j.tics.2016.03.014 [Students not working in imaging can skip over most of the technical details in this article. Read it as a model for taking measurement seriously in an emerging area of clinical research.]

Haynes, S. N., & Yoshioka, D. T. (2007). Clinical assessment applications of ambulatory biosensors. *Psychological Assessment, 19*(1), 44–57. https://doi.org/10.1037/1040-3590.19.1.44 

Kozak, M. J., & Cuthbert, B. N. (2016). The NIMH research domain criteria initiative: Background, issues, and pragmatics. *Psychophysiology, 53*(3), 286–297. https://doi.org/10.1111/psyp.12518 [Students already familiar with RDoC can skim this introduction. Our interest is in examining RDoC from a measurement perspective.]

MacNamara, A., & Phan, K. L. (2016). Psychobiological operationalization of RDoC constructs: Methodological and conceptual opportunities and challenges. *Psychophysiology, 53*(3), 406–409. https://doi.org/10.1111/psyp.12587

Miller, G. A., Rockstroh, B. S., Hamilton, H. K., & Yee, C. M. (2016). Psychophysiology as a core strategy in RDoC. *Psychophysiology, 53*(3), 410–414. https://doi.org/10.1111/psyp.12581

Miller, G. A., Elbert, T., Sutton, B. P., & Heller, W. (2007). Innovative clinical assessment technologies: Challenges and opportunities in neuroimaging. *Psychological Assessment, 19*(1), 58–73. https://doi.org/10.1037/1040-3590.19.1.58

### Computers and Adaptive Testing

<u>Section 25</u>

Buchanan, T. (2002). Online assessment: Desirable or dangerous? *Professional Psychology: Research and Practice, 33*(2), 148–154. https://doi.org/10.1037/0735-7028.33.2.148

Garb, H. N. (2007). Computer-administered interviews and rating scales. *Psychological Assessment, 19*(1), 4–13. https://doi.org/10.1037/1040-3590.19.1.4

Ruiz, M. A., Drake, E. B., Glass, A., Marcotte, D., & van Gorp, W. G. (2002). Trying to beat the system: Misuse of the internet to assist in avoiding the detection of psychological symptom dissimulation. *Professional Psychology: Research and Practice, 33*(3), 294–299. https://doi.org/10.1037/0735-7028.33.3.294

Forbey, J. D., & Ben-Porath, Y. S. (2007). Computerized adaptive personality testing: A review and illustration with the MMPI-2 computerized adaptive version. *Psychological Assessment, 19*(1), 14–24. https://doi.org/10.1037/1040-3590.19.1.14

Gibbons, R. D., Weiss, D. J., Frank, E., & Kupfer, D. (2016). Computerized adaptive diagnosis and testing of mental health disorders. *Annual Review of Clinical Psychology, 12*(1), 83–104. https://doi.org/10.1146/annurev-clinpsy-021815-093634

## Behavioral Assessment

<u>Section 26</u>

Girard, J. M., & Cohn, J. F. (2016). A primer on observational measurement. *Assessment, 23*(4), 404–413. https://doi.org/10.1177/1073191116635807

Haynes, S. N. (2001). Clinical applications of analogue behavioral observation: dimensions of psychometric evaluation. *Psychological Assessment, 13*(1), 73–85. https://doi.org/10.1037/1040-3590.13.1.73 

Korotitsch, W. J., & Nelson-Gray, R. O. (1999). An overview of self-monitoring research in assessment and treatment. *Psychological Assessment, 11*(4), 415–425. https://doi.org/10.1037/1040-3590.11.4.415 

Piasecki, T. M., Hufford, M. R., Solhan, M., & Trull, T. J. (2007). Assessing clients in their natural environments with electronic diaries: Rationale, benefits, limitations, and barriers. *Psychological Assessment, 19*(1), 25–43. https://doi.org/10.1037/1040-3590.19.1.25

## Repeated Assessments across Time

<u>Section 27</u>

Sobell, L. C., & Sobell, M. B. (2008). Timeline followback (TLFB). In A. J. Rush Jr., M. B. First, & D. Blacker (Eds.), *Handbook of psychiatric measures* (2nd ed., pp. 466–468). American Psychiatric Publishing. 

Carpenter, R. W., Wycoff, A. M., & Trull, T. J. (2016). Ambulatory assessment: New adventures in characterizing dynamic processes. *Assessment, 23*(4), 414–424. https://doi.org/10.1177/1073191116632341 

Matthews, M., Abdullah, S., Murnane, E., Voida, S., Choudhury, T., Gay, G., & Frank, E. (2016). Development and evaluation of a smartphone-based measure of social rhythms for bipolar disorder. *Assessment, 23*(4), 472–483. https://doi.org/10.1177/1073191116656794 [a case study in self-report across time. Specifics of their study are less important.]

<u>Section 28</u>

Hertzog, C., & Nesselroade, J. R. (2003). Assessing psychological change in adulthood: An overview of methodological issues. *Psychology and Aging, 18*(4), 639–657. https://doi.org/10.1037/0882-7974.18.4.639

Petersen, I. T., Choe, D. E., & LeBeau, B. (2020). Studying a moving target in development: The challenge and opportunity of heterotypic continuity. *Developmental Review, 58*, 100935. https://doi.org/10.1016/j.dr.2020.100935

Beltz, A. M., Wright, A. G. C., Sprague, B. N., & Molenaar, P. C. M. (2016). Bridging the nomothetic and idiographic approaches to the analysis of clinical data. *Assessment, 23*(4), 447–458. https://doi.org/10.1177/1073191116648209 [focus on the general issues of combining idiographic and nomothetic data. You don’t need to know the technical details of their GIMME model.]

## Assessment of Cognition

<u>Section 29</u>

\*Busemeyer, J. R., & Stout, J. C. (2002). A contribution of cognitive decision models to clinical assessment: Decomposing performance on the Bechara gambling task. *Psychological Assessment, 14*(3), 253–262. https://doi.org/10.1037/1040-3590.14.3.253

Dunkley, D. M., Segal, Z. V., & Blankstein, K. R. (2019). Cognitive assessment: Issues and methods. In K. S. Dobson & D. J. A. Dozois (Eds.), *Handbook of cognitive-behavioral therapies* (4th ed., pp. 85–119). Guilford Press.

Davison, G. C., Vogel, R. S., & Coffman, S. G. (1997). Think-aloud approaches to cognitive assessment and the articulated thoughts in simulated situations paradigm. *Journal of Consulting and Clinical Psychology, 65*(6), 950–958. https://doi.org/10.1037/0022-006X.65.6.950

Hurlburt, R. T. (1997). Randomly sampling thinking in the natural environment. *Journal of Consulting and Clinical Psychology, 65*(6), 941–949. https://doi.org/10.1037/0022-006X.65.6.941 

Rodebaugh, T. L., Scullin, R. B., Langer, J. K., Dixon, D. J., Huppert, J. D., Bernstein, A., Zvielli, A., & Lenze, E. J. (2016). Unreliability as a threat to understanding psychopathology: The cautionary tale of attentional bias. *Journal of Abnormal Psychology, 125*(6), 840–851. https://doi.org/10.1037/abn0000184 

Treat, T. A., McFall, R. M., Viken, R. J., Kruschke, J. K., Nosofsky, R. M., & Wang, S. S. (2007). Clinical cognitive science: Applying quantitative models of cognitive processing to examine cognitive aspects of psychopathology. In R. W. J. Neufeld (Ed.), *Advances in clinical cognitive science: Formal modeling of processes and symptoms* (pp. 179–205). American Psychological Association. https://doi.org/10.1037/11556-006

</div>

## Cultural and Individual Diversity

<u>Section 30</u>

It may be helpful to review the three Sackett papers and the Cole paper from the Intellectual Assessment section. Also review relevant sections of the APA Standards for Educational and Psychological Testing from the Validity section.

<div style="text-indent: -40px; padding-left: 40px;">

Byrd, D. A., Rivera Mindt, M. M., Clark, U. S., Clarke, Y., Thames, A. D., Gammada, E. Z., & Manly, J. J. (2021). Creating an antiracist psychology by addressing professional complicity in psychological assessment. *Psychological Assessment, 33*(3), 279-285. https://doi.org/10.1037/pas0000993

Okazaki, S., & Sue, S. (1995). Methodological issues in assessment research with ethnic minorities. *Psychological Assessment, 7*(3), 367–375. https://doi.org/10.1037/1040-3590.7.3.367

Garb, H. N. (1997). Race bias, social class bias, and gender bias in clinical judgment. *Clinical Psychology: Science and Practice, 4*(2), 99–120. https://doi.org/10.1111/j.1468-2850.1997.tb00104.x

Leong, F. T. L., & Kalibatseva, Z. (2016). Threats to cultural validity in clinical diagnosis and assessment: Illustrated with the case of Asian Americans. In N. Zane, G. Bernal, & F. T. L. Leong (Eds.), *Evidence-based psychological practice with ethnic minorities: Culturally informed research and clinical strategies* (pp. 57–74). American Psychological Association.

Suzuki, L. A., Onoue, M. A., & Hill, J. S. (2013). Clinical assessment: A multicultural perspective. In K. F. Geisinger, J. F. Carlson, J.-I. C. Hansen, N. R. Kuncel, S. P. Reise, & M. C. Rodriguez (Eds.), *APA handbook of testing and assessment in psychology* (Vol. 2: Testing and assessment in clinical and counseling psychology, pp. 193–212). American Psychological Association. https://doi.org/10.1037/14048-012

</div>

# Grading {#grading}

Final grades will be assigned at the end of the semester on the basis of your total percentage of points earned on examinations and your final paper.
Grades will be assigned on an absolute scale (criterion-referenced grading; see below); course grades will not be curved.
No extra-credit opportunities are available for this course.
Please note: As a matter of fairness to all students, I assign grades based on performance and do not negotiate grades.
Additionally, a penalty of 20% per day will be applied to all assignments turned in late.
Final grades will be assigned based on the following ranges:

| Grade | Percent |
|:------|:--------|
| A+    | 97–100% |
| A     | 93–96   |
| A-    | 90–92   |
| B+    | 87–89   |
| B     | 83–86   |
| B-    | 80–82   |
| C+    | 77–79   |
| C     | 73–76   |
| C-    | 70–72   |
| D+    | 67–69   |
| D     | 63–66   |
| D-    | 60–62   |
| F     | 0–59    |

The relative contribution of each component to your final grade is as follows:

- 30%   Exam 1 (Mid-Term)
- 40%   Exam 2 (Final)
- 30%   Final Paper

# Tentative Course Outline (exam dates fixed) {#outline}

This is a *tentative* course outline.
Changes will be discussed in class.
There are 15 weeks in the semester, and class meets twice per week (30 sections).
We will have one exam during the semester and one final exam during finals week.

| **Section** | **Day** | **Date** | **Content**                                                    |
|-------------|---------|----------|----------------------------------------------------------------|
| 1           | T       | 01/16    | Overview of Class; Clinical Science and the Replication Crisis |
| 2           | Th      | 01/18    | Reliability                                                    |
| 3           | T       | 01/23    | Reliability                                                    |
| 4           | Th      | 01/25    | Validity                                                       |
| 5           | T       | 01/30    | Validity                                                       |
| 6           | Th      | 02/01    | Structural Equation Modeling (SEM)                             |
| 7           | T       | 02/06    | Item Response Theory (IRT)                                     |
| 8           | Th      | 02/08    | Prediction Basics                                              |
| 9           | T       | 02/13    | Signal Detection Theory                                        |
| 10          | Th      | 02/15    | Clinical Judgment vs. Algorithmic Prediction                   |
| 11          | T       | 02/20    | General Issues in Clinical Assessment                          |
| 12          | Th      | 02/22    | Evidence-Based Assessment                                      |
| 13          | T       | 02/27    | Ethical Issues in Assessment                                   |
| 14          | Th      | 02/29    | **Midterm Exam**                                               |
| 15          | T       | 03/05    | Intellectual Assessment                                        |
| 16          | Th      | 03/07    | Intellectual Assessment                                        |
|             | T       | 03/12    | Spring Break!                                                  |
|             | Th      | 03/14    | Spring Break!                                                  |
| 17          | T       | 03/19    | Bias                                                           |
| 18          | Th      | 03/21    | Bias                                                           |
| 19          | T       | 03/26    | The Interview and the DSM                                      |
| 20          | Th      | 03/28    | Objective Personality Testing                                  |
| 21          | T       | 04/02    | Objective Personality Testing                                  |
| 22          | Th      | 04/04    | Objective Personality Testing                                  |
| 23          | T       | 04/09    | Projective Personality Testing                                 |
| 24          | Th      | 04/11    | Psychophysiological Measures and RDoC                          |
| 25          | T       | 04/16    | Computers and Adaptive Testing                                 |
| 26          | Th      | 04/18    | Behavioral Assessment                                          |
| 27          | T       | 04/23    | Repeated Assessments across Time                               |
| 28          | Th      | 04/25    | Repeated Assessments across Time                               |
| 29          | T       | 04/30    | Assessment of Cognition                                        |
| 30          | Th      | 05/02    | Cultural and Individual Diversity; **Final paper due!**        |
| Finals Week |         | TBD (week of 5/6) | **Final Exam**                                        |
    
# Date and Time of the Final Exam {#finalExam}

The final examination date and time will be announced by the Registrar generally by the fifth week of classes and it will be announced on the course ICON site once it is known.
<u>Do not plan your end of the semester travel plans until the final exam schedule is made public.
It is your responsibility to know the date, time, and place of the final exam.</u>
According to Registrar's final exam policy, students <u>have a maximum of two weeks after the announced final exam schedule</u> to request a change if an exam conflict exists or if a student has more than two exams in one day (see the [policy](https://registrar.uiowa.edu/makeup-final-examination-policies) here).

# Course Resources {#courseResources}

There are many course resources available to help you succeed in the class, including:

- Lectures
- Lecture slides
- [Lecture recordings](#recordings)
- Readings
- [Companion book](#textbook)
- Discussions on [ICON](https://icon.uiowa.edu)
- Office hours
- Peer study groups

# Drop Deadline for this Course {#dropDeadline}

You may drop an individual course before the deadline; after this deadline you will need collegiate approval.
You can look up the [drop deadline for this course](https://registrar.uiowa.edu/course-deadlines) here.
When you drop a course, a "W" will appear on your transcript.
The mark of "W" is a neutral mark that does not affect your GPA.
Directions for adding or dropping a course and other registration changes can be found on the [Registrar's website](https://registrar.uiowa.edu/change-registration-myui).
Students can find policies on dropping and withdrawing [here](https://clas.uiowa.edu/students/students-academic-policies/registration-policies#dropping).

# Feedback about the Course {#feedback}

I welcome feedback at any point during the class.
If you have comments on the class or my teaching, please feel free to meet with me during office hours.

## Student Complaints {#complaints}

Students with a complaint about a grade or a related matter should first discuss the situation with the instructor, and finally with the Director or Chair of the school, department, or program offering the course.
Students should contact the CLAS [Associate Dean for Graduate Education and Outreach and Engagement](https://clas.uiowa.edu/deans-office/christine-getz) when additional support is needed.

# Communication: UI Email {#email}

Students are responsible for all official correspondences sent to their UI email address (uiowa.edu) and must use this address for any communication with instructors or staff in the UI community.

# Health and Safety {#health}

The University of Iowa strongly encourages students, faculty, and staff to be vaccinated against COVID-19.
For information about COVID-19 vaccines on campus, please see https://coronavirus.uiowa.edu.
If you are feeling sick, test positive for COVID-19, or may have been exposed to COVID-19, please refer to the campus guidance for the appropriate action (https://coronavirus.uiowa.edu/returning-campus/showing-symptoms).
Regardless of your vaccination status, if you have symptoms consistent with COVID-19, please stay home and follow the appropriate isolation/quarantine guidance.
For up-to-date information throughout the semester, please refer to https://coronavirus.uiowa.edu.

# College of Liberal Arts and Sciences (CLAS) Course Policies {#clasPolicies}

- [Attendance and Absences](https://clas.uiowa.edu/faculty/student-attendance-and-absences)\
University regulations require that students be allowed to make up examinations which have been missed due to illness or other unavoidable circumstances.
Students with mandatory religious obligations or UI authorized activities must discuss their absences with me or the TA as soon as possible.
Religious obligations must be communicated within the first three weeks of classes.
- [Exam Policies](https://clas.uiowa.edu/faculty/examination-policies-and-best-practices)

## Other Expectations of Student Performance {#otherExpectations}

Students have the right to a distraction-free learning environment.
You have the responsibility to help create such a classroom environment.
Please treat other students in the class and the instructor with respect.
Students are expected to help each other learn and to contribute overall to the learning environment of the course.
Arriving prepared for class is part of this expectation.

# University Policies {#UIowaPolicies}

- [Accommodations for Students with Disabilities](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#accommodations-for-students-with-disabilities)
- [Basic Needs and Support for Students](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#basic-needs-and-support-for-students)
- [Classroom Expectations](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#classroom-expectations)
- [Exam Make-up Owing to Absence](https://opsmanual.uiowa.edu/students/absences-class#8.1)
- [Free Speech and Expression](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#free-speech-and-expression)
- [Mental Health](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#mental-health)
- [Military Service Obligations](https://opsmanual.uiowa.edu/students/absences-class#8.3)
- [Non-discrimination](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#non-discrimination-statement)
- [Religious Holy Days](https://opsmanual.uiowa.edu/students/absences-class#8.2)
- [Sexual Harassment/Misconduct and Supportive Measures](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#sexual-harassment--sexual-misconduct-and-supportive-measures)
- [Sharing of Class Recordings](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#sharing-of-class-recordings-if-appropriate)

# Resources for Help {#resources}

- Academic accommodations: https://sds.studentlife.uiowa.edu
- Student care and assistance: https://basicneeds.uiowa.edu/resources/student-care-and-assistance

If you feel that you or someone you know may be struggling with an academic, emotional, or psychological problem, the following organizations are available for assistance:

| Service                                                                    | Contact Info                                                     |
|:---------------------------------------------------------------------------|:-----------------------------------------------------------------|
| University of Iowa Academic Advising Center                                | 353-5700, https://advisingcenter.uiowa.edu                       |
| University Counseling Services                                             | 335-7294, https://www.uiowa.edu/ucs                              |
| Student Health Service - Mental Health                                     | 335-8394, https://studenthealth.uiowa.edu/services/psychiatry    |
| University of Iowa Hospitals and Clinics Adult Psychiatry Services Clinic  | 353-6314, https://www.uihealthcare.org/Psychiatry                |
| Seashore Clinic (in the UI Department of Psychological and Brain Sciences) | 335-2467, https://psychology.uiowa.edu/resources/seashore-clinic |
| Women's Resource and Action Center                                         | 335-1486, https://wrac.uiowa.edu                                 |
| Rape Victim Advocacy Program                                               | 319-335-6000 or 800-228-1625, https://www.uiowa.edu/~rvap        |
| Office of Sexual Misconduct                                                | 319-335-6200, https://osmrc.uiowa.edu                            |
| CommUnity                                                                  | 855-325-4296, https://builtbycommunity.org/crisis                |
| Community & Family Resources                                               | 351-4357, https://www.cfrhelps.org/                              |

<u>If you or someone you know is contemplating suicide</u>, either call or text the Suicide and Crisis Lifeline at 988, or call 911.

# Disclaimer {#disclaimer}

This syllabus is subject to change.
Any changes will be discussed in class, via email, and/or on ICON.
